#!/usr/bin/php
<?php

require("bootstrap.php");

$app = new Strukt\Console\Application("Strukt Ssl");
$app->add(new Strukt\Console\Command\KeyPairGenerate);
$app->add(new Strukt\Console\Command\Encrypt);
$app->add(new Strukt\Console\Command\Decrypt);
$app->add(new Strukt\Console\Command\Certificate);
$app->add(new Strukt\Console\Command\CertificateSelfSign);
$app->add(new Strukt\Console\Command\CertificateVerify);
$app->add(new Strukt\Console\Command\CertificateExtractPublicKey);
$app->add(new Strukt\Console\Command\DumpCfg);
$app->add(new Strukt\Console\Command\Sha);
exit($app->run($_SERVER["argv"]));